### PR TITLE
I add the main skeleton of Flutter

### PR DESCRIPTION
**Pull request by martinalturria**
Start the Flutter project for the Silver Express app

### CODE REVIEW

**Review by manduinca — CHANGES_REQUESTED** [review]
Please add the next files before push your project:

https://github.com/flutter/flutter/blob/master/.gitattributes
https://github.com/flutter/flutter/blob/master/.gitignore

**Comment by martinalturria** [comment]
Hello Jean, good morning. I already added the files you asked for, could you review it to see if I did it right?

**Review by manduinca — APPROVED** [review]
LGTM!

**Review by roquemolina — APPROVED** [review]
I approve PR to start with the folder structure

**Pull request merged**
